export const CACHE_TTL = 0;
export const PUBLISH_WATA_CACHEKEY = 'GET_PUBLISH_WATA_CACHE';
export const PUBLISH_WATA_FOR_SUMMARY_CACHEKEY =
  'PUBLISH_WATA_FOR_SUMMARY_CACHEKEY';
export const KEYWORD_CACHEKEY = 'GET_KEYWORD_CACHE';
export const KEYWORDS_CACHEKEY = 'GET_KEYWORDS_CACHE';

export const BANNER_CACHEKEY = 'GET_BANNER_CACHE';
